info:
  description: Spring Cloud Samples
  url: https://github.com/spring-cloud-samples

---
spring:
  profiles: cloud
  cloud:
    config:
      uri: ${vcap.services.${PREFIX:}configserver.credentials.uri:http://${PREFIX:}${configserver.${application.domain:cfapps.io}}}
cloudfoundry:
  sso:
    tokenUri: ${vcap.services.${PREFIX:}uaa.credentials.tokenUri:}
    authorizationUri: ${vcap.services.${PREFIX:}uaa.credentials.authorizationUri:}
    tokenInfoUri: ${vcap.services.${PREFIX:}uaa.credentials.tokenInfoUri:}
    clientId: ${vcap.services.${PREFIX:}uaa.credentials.clientId:}
    clientSecret: ${vcap.services.${PREFIX:}uaa.credentials.clientSecret:}
  resource:
    tokenInfoUri: ${vcap.services.${PREFIX:}resource.credentials.tokenInfoUri:}
    clientId: ${vcap.services.${PREFIX:}resource.credentials.clientId:}
    clientSecret: ${vcap.services.${PREFIX:}resource.credentials.clientSecret:}
    serviceId: ${PREFIX:}resource
application:
  domain: ${APPLICATION_DOMAIN:cfapps.io}
endpoints:
  restart: enabled
eureka:
  instance:
    hostname: ${PREFIX:}${spring.application.name}.${application.domain:cfapps.io}
    nonSecurePort: 80
  client:
    serviceUrl:
      defaultZone: ${vcap.services.${PREFIX:}eureka.credentials.uri:http://${PREFIX:}eureka.${application.domain:cfapps.io}}/eureka/

---
spring:
  profiles: docker
  cloud:
    config:
      uri: http://${CONFIGSERVER_1_PORT_8888_TCP_ADDR:localhost}:8888
  datasource:
    username: dbuser
    password: '{cipher}AQA+I7kOeNrjEig8pUM+AXSGmD0+M0SHPmIk8Mv7ou0JgyCHRf9EFe7er9zPRIGQISe81Xuoyx3tO6NiAkUe4Q3Xy3u17k1AsGWqLYTaM6wGL+qoJHwm8RsS7Z0bbC596Nq69hFLZj8r80+dSFy9HOvGlkisSCWYLQIne7IuUlHKfma+kNm+e5LIM0CveSojYefROP5acqJ2SbJsFDvXkzCuvp9/uaovBIH2CXHX/iXAS7uuoAD4JE2vFTC9sMYosralNE8vLrb8dkQuYCXTgJ+p9eXm9LisAfKU4p64/EcT/Jsi3azzeFeENe0iBmSXqipfEU6sbDKoBVjsOzvXh3Dvtprib110kpHgOl0gilronR9Nt19A9tkqkHgUs4NCFa8='
endpoints:
  restart: enabled
eureka:
  instance:
    nonSecurePort: 80
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://${EUREKA_1_PORT_8761_TCP_ADDR:localhost}:8761/eureka/
